/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package eu.including.uxv.commands;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum TaskResultType { 
  COMPLETED, ONGOING, BLOCKED, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TaskResultType\",\"namespace\":\"eu.including.uxv.commands\",\"symbols\":[\"COMPLETED\",\"ONGOING\",\"BLOCKED\",\"FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
